#!/bin/bash
# Software License Agreement (BSD License)
#
# Copyright (c) 2013-2015, G.A. vd. Hoorn, TU Delft Robotics Institute
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of the TU Delft Robotics Institute nor the names
#    of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written
#    permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# usage:
#
#   urdf2dae URDF
#


# check command line params
if [ $# -ne 1 ]; then
  echo -e "Usage: `basename ${0}` URDF\n"
  exit 64
fi

# check file exists
if [ ! -e "${1}" ]; then
  echo -e "No such file '${1}'\n"
  exit 74
fi


ABS_INPUT=`readlink -e ${1}`
URDF_NAME=`basename ${ABS_INPUT}`
BASE_INPUT=`basename ${URDF_NAME} urdf`
DAE_NAME="${BASE_INPUT}dae"
DAE_ROUNDED="${BASE_INPUT}rounded.dae"
ABS_OUTPUT=`readlink -e .`/${DAE_NAME}
ABS_ROUNDED=`readlink -e .`/${DAE_ROUNDED}


rosrun collada_urdf urdf_to_collada ${ABS_INPUT} ${ABS_OUTPUT}

rosrun moveit_ikfast round_collada_numbers.py ${ABS_OUTPUT} ${ABS_ROUNDED} 5 >> /dev/null

/usr/bin/openrave0.8-robot.py --info=links ${ABS_OUTPUT}
